`timescale 1ns/1ps


// Test bench generated by Claude

// iverilog -g2012 -o nn_sim nn_components.v nn_components_tb.v
// vvp nn_sim

// TODO: Add comprehensive testing with actual mushrooms (so far testing one neuron at a time)


module nn_components_tb;

    // -------------------------------------------------------
    // Shared signals — primitives
    // -------------------------------------------------------
    reg  signed [7:0]  a, b;
    wire signed [7:0]  sat_sum;
    wire signed [15:0] product;
    wire        [7:0]  relu_out;

    // -------------------------------------------------------
    // Instantiate primitive modules
    // -------------------------------------------------------
    saturated_adder_8bit DUT_ADD (
        .a(a), .b(b), .sum_out(sat_sum)
    );

    multiplier_8bit DUT_MUL (
        .a(a), .b(b), .prod_out(product)
    );

    relu_8bit DUT_RELU (
        .data_in(a), .data_out(relu_out)
    );

    // -------------------------------------------------------
    // Neuron DUT — small 3-input neuron for isolated testing.
    // Using N_INPUTS=3 keeps the expected values hand-checkable.
    // -------------------------------------------------------
    localparam N = 3;

    reg  signed [7:0] n_inputs  [0:N-1];
    reg  signed [7:0] n_weights [0:N-1];
    reg  signed [7:0] n_bias;
    wire signed [7:0] n_out_relu;
    wire signed [7:0] n_out_raw;

    // One instance with ReLU (hidden-layer behaviour)
    neuron #(.N_INPUTS(N), .USE_RELU(1)) DUT_NEURON_RELU (
        .inputs(n_inputs),
        .weights(n_weights),
        .bias(n_bias),
        .activation(n_out_relu)
    );

    // One instance without ReLU (output-layer behaviour)
    neuron #(.N_INPUTS(N), .USE_RELU(0)) DUT_NEURON_RAW (
        .inputs(n_inputs),
        .weights(n_weights),
        .bias(n_bias),
        .activation(n_out_raw)
    );

    // -------------------------------------------------------
    // Helper: print primitive test row
    // -------------------------------------------------------
    task show;
        input signed [7:0] in_a;
        input signed [7:0] in_b;
        begin
            a = in_a;
            b = in_b;
            #1;
            $display("  a=%4d  b=%4d  |  sat_add=%4d  mul=%6d  relu(a)=%4d",
                      $signed(a), $signed(b),
                      $signed(sat_sum),
                      $signed(product),
                      relu_out);
        end
    endtask

    // -------------------------------------------------------
    // Helper: set neuron inputs and print result.
    //
    // Hand-calculated expected value (for N=3):
    //   acc  = bias + i0*w0 + i1*w1 + i2*w2   (exact integer)
    //   scaled = acc / 32  (Q3.5 de-quantise, truncated toward zero)
    //   saturated = clamp(scaled, -128, 127)
    //   relu_out  = max(saturated, 0)
    // -------------------------------------------------------
    task run_neuron;
        input signed [7:0] i0, i1, i2;
        input signed [7:0] w0, w1, w2;
        input signed [7:0] bias;
        input signed [7:0] expect_relu;
        input signed [7:0] expect_raw;
        input [127:0] label;       // 16-char string tag
        integer acc;
        integer scaled;
        begin
            n_inputs[0]  = i0; n_inputs[1]  = i1; n_inputs[2]  = i2;
            n_weights[0] = w0; n_weights[1] = w1; n_weights[2] = w2;
            n_bias       = bias;
            #1;

            // replicate expected arithmetic for the display column
            acc    = $signed(bias)
                   + $signed(i0)*$signed(w0)
                   + $signed(i1)*$signed(w1)
                   + $signed(i2)*$signed(w2);
            scaled = acc / 32;  // integer division truncates — matches >>> in HW
            if (scaled >  127) scaled =  127;
            if (scaled < -128) scaled = -128;

            $display("  %-16s | acc=%6d  scaled=%4d  relu=%4d (exp %4d) %s  raw=%4d (exp %4d) %s",
                      label,
                      acc, scaled,
                      $signed(n_out_relu), $signed(expect_relu),
                      ($signed(n_out_relu) === $signed(expect_relu)) ? "OK" : "FAIL",
                      $signed(n_out_raw),  $signed(expect_raw),
                      ($signed(n_out_raw)  === $signed(expect_raw))  ? "OK" : "FAIL");
        end
    endtask

    // -------------------------------------------------------
    // Test vectors
    // -------------------------------------------------------
    initial begin

        // ===================================================
        // Section 1: Primitives (unchanged)
        // ===================================================
        $display("=== Saturated Adder / Multiplier / ReLU ===\n");

        $display("-- Positive saturation --");
        show(127,   1);
        show(100,  50);
        show( 64,  64);

        $display("\n-- Negative saturation --");
        show(-128,  -1);
        show(-100, -50);
        show( -64, -65);

        $display("\n-- Normal addition --");
        show(  10,  20);
        show( -10,  10);
        show(  50, -20);

        $display("\n-- Multiplier edge cases --");
        show(  10,  10);
        show( -10,  10);
        show( -10, -10);
        show( 127, 127);
        show(-128,-128);

        $display("\n-- ReLU --");
        show(   5,  0);
        show(   0,  0);
        show(  -1,  0);
        show(-128,  0);
        show( 127,  0);

        // ===================================================
        // Section 2: Neuron module
        //
        // Columns: acc = raw dot-product+bias before Q3.5 shift
        //          scaled = acc/32 (what hardware produces after >>>5)
        //          relu = max(scaled,0)   raw = scaled (no clamp)
        // ===================================================
        $display("\n\n=== Neuron module (N_INPUTS=3, Q3.5 weights) ===");
        $display("    All weights/biases are Q3.5 integers (real = val/32)\n");

        // --- Basic positive activation ---
        // inputs=[1,1,1] weights=[32,32,32] bias=0
        // acc = 0 + 32+32+32 = 96 → scaled=3 → relu=3  raw=3
        $display("-- Positive activation --");
        run_neuron(1,1,1,  32,32,32,  0,  3, 3, "all-ones     ");

        // inputs=[1,1,1] weights=[32,32,32] bias=32
        // acc = 32 + 96 = 128 → scaled=4 → relu=4  raw=4
        run_neuron(1,1,1,  32,32,32,  32,  4, 4, "with bias    ");

        // --- Negative activation: ReLU clamps, raw passes through ---
        // inputs=[1,1,1] weights=[-32,-32,-32] bias=0
        // acc = -96 → scaled=-3 → relu=0  raw=-3
        $display("\n-- Negative activation (ReLU vs raw) --");
        run_neuron(1,1,1,  -32,-32,-32,  0,  0,-3, "neg weights  ");

        // inputs=[1,1,0] weights=[-32,-32,0] bias=32
        // acc = 32 - 32 - 32 + 0 = -32 → scaled=-1 → relu=0  raw=-1
        run_neuron(1,1,0,  -32,-32,0,  32,  0,-1, "bias vs neg  ");

        // --- Zero output ---
        // inputs=[0,0,0] any weights, bias=0 → acc=0 → 0
        $display("\n-- Zero cases --");
        run_neuron(0,0,0,  64,64,64,  0,  0, 0, "zero inputs  ");

        // inputs=[1,-1,0] weights=[32,32,0] bias=0
        // acc = 32*1 + 32*(-1) = 0 → scaled=0 → 0
        run_neuron(1,-1,0,  32,32,0,  0,  0, 0, "cancel out   ");

        // --- Q3.5 rounding: acc not divisible by 32 ---
        // inputs=[1,1,1] weights=[10,10,10] bias=0
        // acc=30 → 30/32=0 (truncated) → relu=0  raw=0
        $display("\n-- Q3.5 sub-threshold (acc < 32) --");
        run_neuron(1,1,1,  10,10,10,  0,  0, 0, "sub-thresh   ");

        // acc=31 → 31/32=0
        run_neuron(1,1,1,  10,10,11,  0,  0, 0, "just below 32");

        // acc=32 → 32/32=1
        run_neuron(1,1,1,  10,11,11,  0,  1, 1, "exactly 32   ");

        // --- Positive saturation: scaled > 127 ---
        // inputs=[1,1,1] weights=[127,127,127] bias=0
        // acc=381 → scaled=11 → no saturation
        // To force saturation use large weights:
        // weights=[127,127,127] bias=127 → acc=381+127=508 → scaled=15 → no sat
        // Need scaled>127: acc must be >127*32=4064
        // inputs=[1,1,1] weights=[127,127,127] bias=127 → acc=508 → scaled=15
        // Use inputs=[127,127,127]:
        // acc = 0 + 127*127*3 = 48387 → scaled=1511 → saturates to 127
        $display("\n-- Output saturation --");
        run_neuron(127,127,127,  127,127,127,  0,  127, 127, "pos saturate ");

        // Negative saturation: inputs=[127,127,127] weights=[-127,-127,-127]
        // acc = -48387 → scaled=-1511 → saturates to -128
        // relu=0, raw=-128
        run_neuron(127,127,127,  -127,-127,-127,  0,  0,-128, "neg saturate ");

        // --- Mixed-sign dot product ---
        // inputs=[1,-1,1] weights=[64,-64,32] bias=0
        // acc = 64 + 64 + 32 = 160 → scaled=5 → relu=5  raw=5
        $display("\n-- Mixed signs --");
        run_neuron(1,-1,1,  64,-64,32,  0,  5, 5, "mixed inputs ");

        // inputs=[2,3,-1] weights=[32,16,-32] bias=16
        // acc = 16 + 64 + 48 + 32 = 160 → scaled=5 → relu=5  raw=5
        run_neuron(2,3,-1,  32,16,-32,  16,  5, 5, "mixed all    ");

        $display("\n=== Done ===");
        $finish;
    end

endmodule